name: Linux
run-name: Linux
on:
  pull_request:
    paths-ignore:
    - README.md
    types: [ opened, reopened, synchronize]
  workflow_dispatch:
    
jobs:
  Kokkos-040300-OpenMP-Release:
    env:
      KOKKOS_SRC: ${{ github.workspace }}/_deps/kokkos
      KOKKOS_BUILD: ${{ github.workspace }}/_deps/kokkos-build
      KOKKOS_INSTALL: ${{ github.workspace }}/_deps/kokkos-install
      MINIAERO_SRC: ${{ github.workspace }}
      MINIAERO_BUILD: ${{ github.workspace }}/build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Kokkos
        run: |
          git clone --branch 4.3.00 --depth 1 https://github.com/kokkos/kokkos.git "$KOKKOS_SRC"
          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Release -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_NATIVE=ON
          cmake --build "$KOKKOS_BUILD" --parallel $(nproc) -t install
      - name: Build miniAero
        run: |
          cmake -S "$MINIAERO_SRC"/kokkos -B "$MINIAERO_BUILD" -DMINIAERO_ENABLE_MPI=OFF -DMINIAERO_EXTERNAL_KOKKOS=ON -DKokkos_ROOT="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Release
          VERBOSE=1 cmake --build "$MINIAERO_BUILD"
      - name: Test miniAero
        run: |
          ctest -V --test-dir "$MINIAERO_BUILD" --rerun-failed --output-on-failure
  Kokkos-040300-OpenMP-Debug:
    env:
      KOKKOS_SRC: ${{ github.workspace }}/_deps/kokkos
      KOKKOS_BUILD: ${{ github.workspace }}/_deps/kokkos-build
      KOKKOS_INSTALL: ${{ github.workspace }}/_deps/kokkos-install
      MINIAERO_SRC: ${{ github.workspace }}
      MINIAERO_BUILD: ${{ github.workspace }}/build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Kokkos
        run: |
          git clone --branch 4.3.00 --depth 1 https://github.com/kokkos/kokkos.git "$KOKKOS_SRC"
          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Debug -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_NATIVE=ON
          cmake --build "$KOKKOS_BUILD" --parallel $(nproc) -t install
      - name: Build miniAero
        run: |
          cmake -S "$MINIAERO_SRC"/kokkos -B "$MINIAERO_BUILD" -DMINIAERO_ENABLE_MPI=OFF -DMINIAERO_EXTERNAL_KOKKOS=ON -DKokkos_ROOT="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Debug
          VERBOSE=1 cmake --build "$MINIAERO_BUILD"
      - name: Test miniAero
        run: |
          ctest -V --test-dir "$MINIAERO_BUILD" --rerun-failed --output-on-failure
  Kokkos-040300-Serial-Release:
    env:
      KOKKOS_SRC: ${{ github.workspace }}/_deps/kokkos
      KOKKOS_BUILD: ${{ github.workspace }}/_deps/kokkos-build
      KOKKOS_INSTALL: ${{ github.workspace }}/_deps/kokkos-install
      MINIAERO_SRC: ${{ github.workspace }}
      MINIAERO_BUILD: ${{ github.workspace }}/build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Kokkos
        run: |
          git clone --branch 4.3.00 --depth 1 https://github.com/kokkos/kokkos.git "$KOKKOS_SRC"
          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Release -DKokkos_ENABLE_SERIAL=ON -DKokkos_ARCH_NATIVE=ON
          cmake --build "$KOKKOS_BUILD" --parallel $(nproc) -t install
      - name: Build miniAero
        run: |
          cmake -S "$MINIAERO_SRC"/kokkos -B "$MINIAERO_BUILD" -DMINIAERO_ENABLE_MPI=OFF -DMINIAERO_EXTERNAL_KOKKOS=ON -DKokkos_ROOT="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Release
          VERBOSE=1 cmake --build "$MINIAERO_BUILD"
      - name: Test miniAero
        run: |
          ctest -V --test-dir "$MINIAERO_BUILD" --rerun-failed --output-on-failure
  Kokkos-040300-Serial-Debug:
    env:
      KOKKOS_SRC: ${{ github.workspace }}/_deps/kokkos
      KOKKOS_BUILD: ${{ github.workspace }}/_deps/kokkos-build
      KOKKOS_INSTALL: ${{ github.workspace }}/_deps/kokkos-install
      MINIAERO_SRC: ${{ github.workspace }}
      MINIAERO_BUILD: ${{ github.workspace }}/build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Kokkos
        run: |
          git clone --branch 4.3.00 --depth 1 https://github.com/kokkos/kokkos.git "$KOKKOS_SRC"
          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Debug -DKokkos_ENABLE_SERIAL=ON -DKokkos_ARCH_NATIVE=ON
          cmake --build "$KOKKOS_BUILD" --parallel $(nproc) -t install
      - name: Build miniAero
        run: |
          cmake -S "$MINIAERO_SRC"/kokkos -B "$MINIAERO_BUILD" -DMINIAERO_ENABLE_MPI=OFF -DMINIAERO_EXTERNAL_KOKKOS=ON -DKokkos_ROOT="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Debug
          VERBOSE=1 cmake --build "$MINIAERO_BUILD"
      - name: Test miniAero
        run: |
          ctest -V --test-dir "$MINIAERO_BUILD" --rerun-failed --output-on-failure
  Kokkos-040300-Serial-Debug-SplitKernel:
    env:
      KOKKOS_SRC: ${{ github.workspace }}/_deps/kokkos
      KOKKOS_BUILD: ${{ github.workspace }}/_deps/kokkos-build
      KOKKOS_INSTALL: ${{ github.workspace }}/_deps/kokkos-install
      MINIAERO_SRC: ${{ github.workspace }}
      MINIAERO_BUILD: ${{ github.workspace }}/build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Kokkos
        run: |
          git clone --branch 4.3.00 --depth 1 https://github.com/kokkos/kokkos.git "$KOKKOS_SRC"
          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Debug -DKokkos_ENABLE_SERIAL=ON -DKokkos_ARCH_NATIVE=ON
          cmake --build "$KOKKOS_BUILD" --parallel $(nproc) -t install
      - name: Build miniAero
        run: |
          cmake -S "$MINIAERO_SRC"/kokkos -B "$MINIAERO_BUILD" -DMINIAERO_ENABLE_MPI=OFF -DMINIAERO_EXTERNAL_KOKKOS=ON -DKokkos_ROOT="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Debug -DMINIAERO_SPLIT_COMPUTE_TAGENTBC_FLUX=ON
          VERBOSE=1 cmake --build "$MINIAERO_BUILD"
      - name: Test miniAero
        run: |
          ctest -V --test-dir "$MINIAERO_BUILD" --rerun-failed --output-on-failure
  Kokkos-040300-Serial-Release-HostOpts:
    env:
      KOKKOS_SRC: ${{ github.workspace }}/_deps/kokkos
      KOKKOS_BUILD: ${{ github.workspace }}/_deps/kokkos-build
      KOKKOS_INSTALL: ${{ github.workspace }}/_deps/kokkos-install
      MINIAERO_SRC: ${{ github.workspace }}
      MINIAERO_BUILD: ${{ github.workspace }}/build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Kokkos
        run: |
          git clone --branch 4.3.00 --depth 1 https://github.com/kokkos/kokkos.git "$KOKKOS_SRC"
          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Release -DKokkos_ENABLE_SERIAL=ON -DKokkos_ARCH_NATIVE=ON
          cmake --build "$KOKKOS_BUILD" --parallel $(nproc) -t install
      - name: Build miniAero
        run: |
          cmake -S "$MINIAERO_SRC"/kokkos -B "$MINIAERO_BUILD" -DMINIAERO_ENABLE_MPI=OFF -DMINIAERO_EXTERNAL_KOKKOS=ON -DKokkos_ROOT="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Release -DMINIAERO_KOKKOS_REDUCE_MINMAX_HOST=ON -DMINIAERO_KOKKOS_BINSORT_HOST=ON
          VERBOSE=1 cmake --build "$MINIAERO_BUILD"
      - name: Test miniAero
        run: |
          ctest -V --test-dir "$MINIAERO_BUILD" --rerun-failed --output-on-failure
  Kokkos-Internal-Serial-Release:
    env:
      MINIAERO_SRC: ${{ github.workspace }}
      MINIAERO_BUILD: ${{ github.workspace }}/build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build miniAero
        run: |
          cmake -S "$MINIAERO_SRC"/kokkos -B "$MINIAERO_BUILD" -DMINIAERO_ENABLE_MPI=OFF -DCMAKE_BUILD_TYPE=Release
          VERBOSE=1 cmake --build "$MINIAERO_BUILD"
      - name: Test miniAero
        run: |
          ctest -V --test-dir "$MINIAERO_BUILD" --rerun-failed --output-on-failure
