name: Linux MPI (Build Only)
run-name: Linux MPI (Build Only)
on:
  pull_request:
    paths-ignore:
    - README.md
    types: [ opened, reopened, synchronize]
  workflow_dispatch:
    
jobs:
   Kokkos-040300-OpenMPI-OpenMP-Release:
    env:
      KOKKOS_SRC: ${{ github.workspace }}/_deps/kokkos
      KOKKOS_BUILD: ${{ github.workspace }}/_deps/kokkos-build
      KOKKOS_INSTALL: ${{ github.workspace }}/_deps/kokkos-install
      MINIAERO_SRC: ${{ github.workspace }}
      MINIAERO_BUILD: ${{ github.workspace }}/build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install Packages
        run: |
          sudo apt-get update && sudo apt-get install -y libopenmpi-dev openmpi-bin cmake
          which cmake
          cmake --version
          which mpirun
          mpirun --version
          which mpicxx
          mpicxx --version
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Kokkos
        run: |
          git clone --branch 4.3.00 --depth 1 https://github.com/kokkos/kokkos.git "$KOKKOS_SRC"
          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Release -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_NATIVE=ON
          cmake --build "$KOKKOS_BUILD" --parallel $(nproc) -t install
      - name: Build miniAero
        run: |
          cmake -S "$MINIAERO_SRC"/kokkos -B "$MINIAERO_BUILD" -DMINIAERO_EXTERNAL_KOKKOS=ON -DKokkos_ROOT="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Release
          VERBOSE=1 cmake --build "$MINIAERO_BUILD"
   Kokkos-040300-OpenMPI-OpenMP-Debug:
    env:
      KOKKOS_SRC: ${{ github.workspace }}/_deps/kokkos
      KOKKOS_BUILD: ${{ github.workspace }}/_deps/kokkos-build
      KOKKOS_INSTALL: ${{ github.workspace }}/_deps/kokkos-install
      MINIAERO_SRC: ${{ github.workspace }}
      MINIAERO_BUILD: ${{ github.workspace }}/build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install Packages
        run: |
          sudo apt-get update && sudo apt-get install -y libopenmpi-dev openmpi-bin cmake
          which cmake
          cmake --version
          which mpirun
          mpirun --version
          which mpicxx
          mpicxx --version
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Kokkos
        run: |
          git clone --branch 4.3.00 --depth 1 https://github.com/kokkos/kokkos.git "$KOKKOS_SRC"
          cmake -S "$KOKKOS_SRC" -B "$KOKKOS_BUILD" -DCMAKE_INSTALL_PREFIX="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Debug -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_NATIVE=ON
          cmake --build "$KOKKOS_BUILD" --parallel $(nproc) -t install
      - name: Build miniAero
        run: |
          cmake -S "$MINIAERO_SRC"/kokkos -B "$MINIAERO_BUILD" -DMINIAERO_EXTERNAL_KOKKOS=ON -DKokkos_ROOT="$KOKKOS_INSTALL" -DCMAKE_BUILD_TYPE=Debug
          VERBOSE=1 cmake --build "$MINIAERO_BUILD"
